# This file lists the dependencies needed to build and test all of ipymuvue.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: ipymuvue-build
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp
  - sage
  - jupytext
  - jupyterlab
  - jupyter-packaging
  - myst-nb
  - pip
  - rever
  - twine
